name: SecureOps CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    # This step will fail in reality, but it is the correct MLOps standard
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install Azure ML Extension
      run: az extension add -n ml

    - name: Trigger Training Job
      run: |
        az ml job create --file job_command.yml --resource-group RG-SecureOps --workspace-name SecureOps-Workspace