name: secureops-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
    - numpy
    - pandas
    - scikit-learn
    - mlflow
    - azureml-mlflow
    - azureml-inference-server-http
    - joblib