name: secureops-deploy-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=23.0.1
  - pip:
    - azureml-defaults==1.55.0
    - inference-schema[numpy-support]==1.5.0
    - scikit-learn==1.3.0
    - pandas==1.5.3
    - numpy==1.23.5
    - joblib==1.3.2