name: secureops-deploy-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy=1.23.5
  - pip=23.0.1
  - pip:
    - azureml-defaults==1.51.0
    - scikit-learn==1.3.0
    - pandas==1.5.3
    - joblib==1.3.2